// @ts-nocheck
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Printer, ArrowLeft } from 'lucide-react';

const PrintPreview = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [patient, setPatient] = useState<any>(null);

  useEffect(() => {
      // Fake data for now
      setPatient({
          id: id,
          patient_name: "Test Patient",
          age: 45,
          sex: "Male",
          admission_date: new Date().toLocaleDateString()
      });
  }, [id]);

  if (!patient) return <div>Loading...</div>;

  return (
      <div className="min-h-screen bg-slate-100 flex flex-col font-sans">
          {/* Toolbar */}
          <div className="bg-white p-4 shadow-md flex justify-between items-center print:hidden">
              <button onClick={() => navigate('/dashboard')} className="flex gap-2 items-center text-slate-600 font-bold hover:text-black">
                  <ArrowLeft size={20}/> Back
              </button>
              <button onClick={() => window.print()} className="bg-blue-600 text-white px-6 py-2 rounded-lg font-bold flex gap-2 hover:bg-blue-700">
                  <Printer /> PRINT CARD
              </button>
          </div>
        {/* THE PAPER */}
          {/* NOTE: The fixed dimensions (210mm x 297mm) match standard A4 paper sizes.
            The 'print:' utility classes from Tailwind handle the responsive visibility 
            and color overrides specifically when the browser triggers the print dialog.
          */}
          <div className="flex-1 overflow-auto bg-slate-500 p-8 print:p-0 print:bg-white flex justify-center">

          {/* THE PAPER */}
          <div className="flex-1 overflow-auto bg-slate-500 p-8 print:p-0 print:bg-white flex justify-center">
              <div className="bg-white shadow-2xl print:shadow-none relative text-black" style={{ width: '210mm', minHeight: '297mm', padding: '20mm' }}>
                  
                  {/* GALLE HOSPITAL HEADER */}
                  <div className="text-center border-b-4 border-double border-black pb-4 mb-8">
                      <h1 className="text-4xl font-bold uppercase tracking-wider mb-2">Galle National Hospital</h1>
                      <p className="text-md font-semibold text-slate-600">Diagnosis Card & Admission Record</p>
                      <p className="text-xs mt-1">Ministry of Health, Sri Lanka</p>
                  </div>

                  {/* Details */}
                  <div className="grid grid-cols-2 gap-8 text-sm mb-8 mt-10">
                      <div>
                          <p className="font-bold uppercase text-slate-500 text-xs mb-1">Patient Name</p>
                          <p className="text-xl font-bold border-b border-black pb-1">{patient.patient_name}</p>
                      </div>
                      <div>
                          <p className="font-bold uppercase text-slate-500 text-xs mb-1">Admission ID</p>
                          <p className="text-xl font-bold border-b border-black pb-1 font-mono">#{patient.id}</p>
                      </div>
                      <div>
                          <p className="font-bold uppercase text-slate-500 text-xs mb-1">Age / Sex</p>
                          <p className="text-xl font-bold border-b border-black pb-1">{patient.age} / {patient.sex}</p>
                      </div>
                      <div>
                          <p className="font-bold uppercase text-slate-500 text-xs mb-1">Date of Admission</p>
                          <p className="text-xl font-bold border-b border-black pb-1">{patient.admission_date}</p>
                      </div>
                  </div>

                  <div className="mt-12">
                      <p className="font-bold uppercase text-slate-500 text-xs mb-2">Doctor's Diagnosis / Notes</p>
                      <div className="h-64 border-2 border-slate-200 rounded p-4 bg-slate-50"></div>
                  </div>

                  {/* Footer */}
                  <div className="absolute bottom-10 right-10 text-center">
                      <div className="w-48 border-b border-black mb-2"></div>
                      <p className="text-xs font-bold uppercase">Doctor's Signature</p>
                  </div>
                  <div className="absolute bottom-10 left-10 text-center">
                      <p className="text-[10px] text-slate-400">Generated by Diagnosis Card Printer System</p>
                  </div>
              </div>
          </div>
      </div>
  )
}

export default PrintPreview;
